@startuml

class Pessoa {
  - Integer id
  - String nome
  - String sobreNome
  - Endereco endereco
  - String email
  - Timestamp dataCadastro
  + adicionar()
  + lista()
  + modificar()
}

class Dentista extends Pessoa {
    - String matricula
    }

class Paciente extends Pessoa {
    - String rg
    + excluir()
}


class Consulta{
    - Paciente paciente
    - Dentista dentista
    - Date dataConsulta
    - Timestamp horaConsulta
}

class Endereco{
 - Integer id
 - String numero
 - String rua
 - String referencia
 - String bairro
 - String cidade
 - String estado
 + adicionar()
 + lista()
 + modificar()
 + excluir()
}

class Usuario{
   - Paciente paciente
   - String user
   - String passwd
   + adicionar()
   + lista()
   + modificar()
   + excluir()
}

Consulta o- Paciente : Agregação
Dentista -o Consulta : Agregação

Pessoa -o Endereco

Dentista --o Usuario
Paciente -o Usuario

@enduml