version: '3.8'
services:
  api:
    container_name: backend_api
    build:
      context: .
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      MYSQL_URL: jdbc:mysql://mysql-db:3306/clinicaodonto?createDatabaseIfNotExist=true&serverTimezone=true&serverTimezone=UTC
    depends_on:
      - mysql-db

  mysql-db:
    container_name: mysql_db
    image: mysql:8.0.4
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 323327Be!
      MYQSL_DATABASE: clinicaodonto

networks:
  backend:
